apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctfd-mysql
  template:
    metadata:
      labels:
        app: ctfd-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ctfd
        - name: MYSQL_DATABASE
          value: ctfd
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-mysql
spec:
  selector:
    app: ctfd-mysql
  ports:
  - port: 3306
